### ISSUE TITLE
Include validity date in returned data frame from getKlass() when a date interval is supplied

### ISSUE THREAD

**Issue by mafw** [statisticsnorway/ssb-klassr#31]
As documented in the [package vignette](https://statisticsnorway.github.io/ssb-klassr/articles/klassR-vignette.html#working-with-dates), GetKlass can be used to fetch all codes for a classification over a period of time by supplying a vector with two dates to the `date` argument in the function call.

However, the returned data frame does not contain information on the dates for which each row/classification is valid. In the example from the vignette, regional codes are fetched for the period 2019 to 2020:
```
GetKlass(106, date = c("2019-01-01", "2020-01-01"))`
```
Which returns a data frame with four columns: code, parentCode, level, and name. 

It would be helpful if the call also returned a column corresponding to the date for which the classification is valid. In the example above then, rows 1 and 2 would in this case get values "2019-01-01" and "2020-01-01" in my proposed "date" column.

**Comment by sjentoft** [comment]
Good suggestion thanks. I have added this in and version 0.2.4 includes returning valid from/to or date of change variables.
