### ISSUE TITLE
klassR:::formattering() breaks when supplied codes with different formatting

### ISSUE THREAD

**Issue by ssb-yib** [statisticsnorway/ssb-klassr#41]
`klassR:::formattering()` appears to break when presented with (valid) input codes that have different formatting than other codes in the classification. The examples below use [Standard for næringsgruppering](https://www.ssb.no/klass/klassifikasjoner/6) in which the top level uses letters, the second level uses digits, and levels 3-5 use a combination of digits and periods:

<pre>
A Jordbruk, skogbruk og fiske
└─ 01 Jordbruk og tjenester tilknyttet jordbruk, jakt og viltstell
   └─ 01.1 Dyrking av ettårige vekster
      └─ 01.10 Dyrking av korn (unntatt ris), belgvekster og oljeholdige vekster
         └─ 01.110 Dyrking av korn (unntatt ris), belgvekster og oljeholdige vekster
</pre>

`formattering()` does not appear to break when supplied codes at different levels in the classification but with the same type of formatting, so the bug seems to be related to codes that are formatted differently (letters vs. digits?).

# Examples

## Works as expected

`formattering()` returns correctly formatted codes for all inputs.

```
> klassR:::formattering(c("01", "011", "0110", "01110"), klass = 6)
[1] "01"     "01.1"   "01.10"  "01.110"
Warning message:
In formattering_nace(x) : Number missing .: 3
```
## Does not work as expected

`formattering()` correctly returns `"A"` for the input `"A"` (a valid code in klass 6), but fails to apply formatting to the other inputs.

```
> klassR:::formattering(c("A", "01", "011", "0110", "01110"), klass = 6)
[1] "A"     "01"    "011"   "0110"  "01110"
```
The order of the inputs does not appear to matter.

```
> inputs <- c("A", "01", "011", "0110", "01110")
> 
> lapply(lapply(1:10, \(x) sample(inputs)), 
+        klassR:::formattering, 
+        klass = 6)
[[1]]
[1] "A"     "01"    "01110" "0110"  "011"  

[[2]]
[1] "01"    "0110"  "A"     "011"   "01110"

[[3]]
[1] "0110"  "01"    "01110" "011"   "A"    

[[4]]
[1] "0110"  "A"     "01110" "01"    "011"  

[[5]]
[1] "0110"  "A"     "01"    "011"   "01110"

[[6]]
[1] "01"    "01110" "011"   "A"     "0110" 

[[7]]
[1] "01"    "011"   "0110"  "01110" "A"    

[[8]]
[1] "A"     "0110"  "011"   "01"    "01110"

[[9]]
[1] "0110"  "011"   "A"     "01"    "01110"

[[10]]
[1] "A"     "01"    "0110"  "01110" "011"  
```

**Comment by sjentoft** [comment]
Thanks Øyvind! This has been fixed in version 0.2.4.
